name: 2Dwg
channels:
  - pytorch
  - defaults
  - conda-forge 
dependencies:
  - python=3.12
  - jupyterlab
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - pytorch=2.5.0
  - torchvision=0.20.0
  - scikit-learn=1.5.1
